import React from 'react';
import {Ledger, ReturnBars, Drivers, Explorer, ReadingProgress, Counter, useReveal} from './components.jsx';
export default function App(){useReveal();return <>
<a className="skip" href="#main">{"Skip to content"}</a><ReadingProgress />
<header className="masthead"><a href="#top" className="brand"><span className="brand-square">{"SP"}</span><span>{"FIELD NOTE "}<b>{"01"}</b></span></a><nav aria-label="Sections"><a href="#method">{"Method"}</a><a href="#performance">{"Performance"}</a><a href="#explorer">{"Explorer"}</a><a href="#conclusion">{"Conclusion"}</a></nav><a className="nav-export" href="#ledger">{"View the ledger "}<span>{"↗"}</span></a></header>
<main id="main">
<section id="top" className="hero wrap"><div className="hero-copy"><p className="eyebrow hero-enter">{"KASHVI TRIBHUVAN / FINANCE STUDY / 2025"}</p><h1><span className="hero-line">{"Stock"}</span><span className="hero-line"><em>{"Investment"}</em></span><span className="hero-line">{"Portfolio"}</span><span className="hero-line">{"Analysis"}<span className="title-dot">{"."}</span></span></h1><p className="hero-description hero-enter">{"Five familiar names. Nine days of observation."}<br />{"A ₹10,00,000 experiment in the quiet power"}<br className="desktop" />{" of diversification."}</p><div className="hero-actions hero-enter"><a className="button primary" href="#method">{"Read the analysis "}<span>{"↘"}</span></a><span className="micro">{"APRIL 2025"}<br />{"INDIA / SIMULATED EQUITIES"}</span></div></div>
<div className="hero-visual hero-enter"><div className="portfolio-card"><div className="card-top micro"><span>{"PORTFOLIO / 001"}</span><span>{"₹ INR"}</span></div><div className="card-graphic" aria-hidden="true"><span style={{"--h": "70%", "--c": "var(--rust)"}}></span><span style={{"--h": "26%", "--c": "var(--sage)"}}></span><span style={{"--h": "8%", "--c": "var(--rust)"}}></span><span style={{"--h": "33%", "--c": "var(--sage)"}}></span><span style={{"--h": "55%", "--c": "var(--rust)"}}></span></div><p className="micro card-label">{"NET RETURN / STUDY WINDOW"}</p><div className="hero-return"><Counter value={-2.32} /><sup>{"%"}</sup></div><p className="card-loss">{"−₹23,240"}</p><div className="card-bottom"><div><span className="micro">{"OPENING VALUE"}</span><strong>{"₹10,00,000"}</strong></div><div><span className="micro">{"ALLOCATION"}</span><strong>{"20% × 5"}</strong></div><span className="stamp">{"SIMULATED"}<br />{"PORTFOLIO"}</span></div></div><div className="visual-caption micro"><span>{"FIVE POSITIONS. ONE SHARED OUTCOME."}</span><span>{"FIG. 01 ↗"}</span></div></div>
<div className="section-end micro"><a href="#method">{"SCROLL TO EXAMINE THE RECORD ↓"}</a><span className="rule"></span><span>{"01 / 06"}</span></div></section>
<div className="ticker" aria-label="Study stock returns"><div className="ticker-inner"><span>{"LT "}<b className="loss">{"−11.12% ↘"}</b></span><span>{"ASIANPAINT "}<b className="gain">{"+4.05% ↗"}</b></span><span>{"ICICIBANK "}<b className="loss">{"−1.15% ↘"}</b></span><span>{"HINDUNILVR "}<b className="gain">{"+5.15% ↗"}</b></span><span>{"TCS "}<b className="loss">{"−8.55% ↘"}</b></span><span className="ticker-label">{"APRIL 2025 / HISTORICAL SIMULATION"}</span></div></div>
<section id="method" className="section brief"><div className="wrap"><p className="section-label reveal"><span>{"01"}</span>{" THE BRIEF"}</p><div className="split"><div className="reveal"><h2>{"One basket."}<br /><em className="gold">{"Five signals."}</em></h2><p className="body-copy">{"When every position starts with the same ₹2,00,000 stake, what does the mix reveal when the market turns uneven?"}</p></div><dl className="spec-list reveal"><div><dt><small>{"A"}</small>{" CAPITAL"}</dt><dd>{"₹10,00,000"}</dd></div><div><dt><small>{"B"}</small>{" CONSTRUCTION"}</dt><dd>{"Equal-weighted"}</dd></div><div><dt><small>{"C"}</small>{" OBSERVATION"}</dt><dd>{"April 2025 · 9-day window"}</dd></div><div><dt><small>{"D"}</small>{" UNIVERSE"}</dt><dd>{"5 Indian companies"}</dd></div><div><dt><small>{"E"}</small>{" METHOD"}</dt><dd>{"Closing-price analysis in Excel"}</dd></div></dl></div></div></section>
<section id="performance" className="section"><div className="wrap"><p className="section-label reveal"><span>{"02"}</span>{" THE LEDGER"}</p><div className="section-heading reveal"><h2>{"Equal weight,"}<br /><em>{"unequal outcome."}</em></h2><p>{"Each holding began at ₹2,00,000."}<br />{"The same starting line."}<br />{"Five very different finishes."}</p></div><Ledger />
<div className="comparison reveal"><div className="chart-title micro"><span>{"PERFORMANCE COMPARISON"}</span><span>{"FIG. 02 / RETURN %"}</span></div><div className="chart-axis micro"><span>{"LOSS"}</span><span>{"0.00"}</span><span>{"GAIN"}</span></div><ReturnBars /><div className="chart-foot micro"><span>{"INDIVIDUAL HOLDING RETURNS"}</span><span>{"−12% ← FIXED SCALE → +12%"}</span></div></div></div></section>
<section id="drivers" className="section dark"><div className="wrap"><p className="section-label reveal"><span>{"03"}</span>{" READING THE MOVE"}</p><div className="section-heading reveal"><h2>{"What moved"}<br /><em className="gold">{"the needle."}</em></h2><p>{"Short windows tell incomplete stories."}<br />{"These are factors considered in the study,"}<br />{"not established causes of each return."}</p></div><Drivers /><div className="dark-foot micro reveal"><span>{"2 POSITIVE HOLDINGS / 3 NEGATIVE HOLDINGS"}</span><span>{"DIFFERENT INDUSTRIES. DIFFERENT PRESSURES."}</span></div></div></section>
<section id="explorer" className="section explorer-section"><div className="wrap"><p className="section-label reveal"><span>{"04"}</span>{" THE EXPLORER"}</p><div className="section-heading reveal"><h2>{"A closer "}<em>{"look."}</em></h2><p>{"Select a holding. Follow its outcome."}<br />{"Explore the arithmetic behind the return."}</p></div><Explorer /><p className="explorer-foot micro">{"ILLUSTRATION: (1 + NINE-DAY RETURN) ^ (DAYS ÷ 9) − 1"}</p></div></section>
<section id="conclusion" className="section conclusion"><div className="wrap"><p className="section-label reveal"><span>{"05"}</span>{" THE READOUT"}</p><div className="split"><div className="reveal"><p className="micro conclusion-kicker">{"DIVERSIFICATION DID ITS QUIET WORK."}</p><h2>{"The loss was"}<br /><em>{"contained,"}<br />{"not erased."}</em></h2></div><div className="conclusion-copy reveal"><p>{"Asian Paints and HUL added "}<strong>{"₹18,400"}</strong>{" together. That offset part of the "}<strong>{"₹41,640"}</strong>{" lost across L&T, ICICI Bank and TCS."}</p><div className="offset"><div><span>{"LOSSES OFFSET BY GAINS"}</span><strong>{"44.2%"}</strong></div><div className="offset-track"><span></span></div></div><p>{"The project proposed reviewing exposure to consumer goods and FMCG. A short observation window supports a discussion about balance; it cannot establish what will outperform next."}</p><a className="button outline" href="#performance">{"Return to the record "}<span>{"↗"}</span></a></div></div><details className="source-notes"><summary>{"Source & methodology notes "}<span>{"+"}</span></summary><div><p>{"Figures come from Kashvi Tribhuvan’s resume and the supplied reference screenshots. The screenshots specify equal 20% allocations. Position changes are calculated as ₹2,00,000 × each reported return and sum to −₹23,240. The exact total return is −2.324%, rounded to −2.32%."}</p><p>{"The reference labels its window 1–9 April 2025; the resume gives an ambiguous “1–9/10 Apr 2025”. This page uses “April 2025 / nine-day observation window” without asserting nine exchange trading sessions. Daily prices are unavailable. Asian Paints is labelled paints & consumer goods here, rather than FMCG as in the reference."}</p><p>{"The compound illustration is a mathematical scenario based on the reported return, not a fitted price path or prediction. All results relate to an academic simulation."}</p></div></details><div className="conclusion-footer micro"><span>{"END OF FIELD NOTE"}</span><span>{"KASHVI TRIBHUVAN / BBA FINANCE"}</span><a href="#top">{"BACK TO TOP ↑"}</a></div></div></section></main><footer className="site-footer micro"><span>{"STOCK INVESTMENT PORTFOLIO ANALYSIS"}</span><span>{"NESS WADIA COLLEGE OF COMMERCE · 2025"}</span></footer>

</>;}
